#!/usr/bin/env python3
#-*- coding:utf-8 -*-
import requests
import pandas as pd

df = pd.read_excel(r"D:\\Python\\test\\【广州东莞】物业汇总表 20170321.xlsx",header=0,sheetname = '增城区')

def map_api(address):
    par = {'address': address, 'key': 'cb649a25c1f81c1451adbeca73623251'}
    base = 'http://restapi.amap.com/v3/geocode/geo'
    response = requests.get(base, par)
    answer = response.json()
    global GPS   #将GPS设置为全局变量
    GPS=answer['geocodes'][0]['location'].split(",")

if __name__ == "__main__":
    for i in range(0,len(df[u'名称'])):   #for i in range(0,len(df[u'名称'])):
        address = "广州市增城区" + df[u'地址'][i]
        print(address)
        map_api(address)
        print(GPS[0] +','+ GPS[1])

        
        

from selenium import webdriver
import requests
import time

def map_api(address):    #通过高德地图API取得所输入地址的————经度GPS[0], 维度GPS[1]  ————import requests
    par = {'address': address, 'key': 'cb649a25c1f81c1451adbeca73623251'}
    base = 'http://restapi.amap.com/v3/geocode/geo'
    response = requests.get(base, par)
    answer = response.json()
    global GPS   #将GPS设置为全局变量
    GPS=answer['geocodes'][0]['location'].split(",")     #.split(",")为将字符串按","切分为列表
    
def open_url(url):     #打开url
    global browser
    browser = webdriver.Firefox()
    browser.get(url)
    time.sleep(1) 
    
if __name__ == "__main__": #定义主程序
    address = '广州市增城区永宁街宁西工业园一路4号'
    map_api(address)
    print(GPS[0] +','+ GPS[1])
    url = "http://ditu.amap.com/regeo?lng="+ GPS[0] + "&lat=" + GPS[1] 
    open_url(url)



    
    

import requests
import pandas as pd

df = pd.read_excel(r"D:\\Python\\test\\【广州东莞】物业汇总表 20170321.xlsx",header=0,sheetname = '增城区')
for i in range(0,len(df[u'名称'])):   #for i in range(0,len(df[u'名称'])):
    address = "广州市增城区" + df[u'地址'][i]
    print(address)
    par = {'address': address, 'key': 'cb649a25c1f81c1451adbeca73623251'}
    base = 'http://restapi.amap.com/v3/geocode/geo'
    response = requests.get(base, par)
    answer = response.json()
    GPS=answer['geocodes'][0]['location'].split(",")
    print(GPS[0] +','+ GPS[1])
    df[u'编号'][i] = GPS[0]
    df[u'后台状态'][i] = GPS[0]
    df.to_csv('invest临时文件.csv')


    
    
    
    
import requests
import pandas as pd
from selenium import webdriver
import time

df = pd.read_excel(r"D:\\Python\\test\\【广州东莞】物业汇总表 20170321.xlsx",header=0,sheetname = '增城区')
for i in range(23,len(df[u'名称'])):   #for i in range(0,len(df[u'名称'])):
    address = "广州市增城区" + df[u'地址'][i]
    print(address)
    par = {'address': address, 'key': 'cb649a25c1f81c1451adbeca73623251'}
    base = 'http://restapi.amap.com/v3/geocode/geo'
    response = requests.get(base, par)
    answer = response.json()
    GPS=answer['geocodes'][0]['location'].split(",")
    print(GPS[0] +','+ GPS[1])
    df[u'编号'][i] = GPS[0]
    df[u'后台状态'][i] = GPS[0]
    browser = webdriver.Firefox()
    browser.get("http://uri.amap.com/marker?position="+GPS[0] +','+ GPS[1])
    time.sleep(3)


    
    


'''
利用高德地图或百度地图api实现地址和经纬度的转换

import requests
import pandas as pd

#使用高德API
def geocodeG(address):
    par = {'address': address, 'key': 'cb649a25c1f81c1451adbeca73623251'}
    base = 'http://restapi.amap.com/v3/geocode/geo'
    response = requests.get(base, par)
    answer = response.json()
    GPS=answer['geocodes'][0]['location'].split(",")
    print(GPS[0] +','+ GPS[1])
    
    return GPS[0],GPS[1]

df = pd.read_excel(r"D:\\Python\\test\\【广州东莞】物业汇总表 20170321.xlsx",header=0,sheetname = '增城区')

for i in range(0,5):   #for i in range(0,len(df[u'名称'])):
    address = "广州市增城区" + df[u'地址'][i]
    print(address)
    geocodeG(address)
    print(GPS[0])
'''
